    install.packages("RStoolbox")   
    library(RStoolbox)
    install.packages("ggplot2") 
    library(ggplot2)
    install.packages("gridExtra") 
    library(gridExtra)
     
   ----------------------------------------------------------------------------------------------------
   
   library(raster)        # the function "library" is used to load and attach added packages
   library(RStoolbox)
   library(ggplot2)
   
   setwd("C:/lab/")   # the "setwd" function changes the current directory to a working directory
    
    
   # brick (importing data)
   
   # 1 list the files available
   rlist <- list.files(pattern= "defor")    # "list.files" creates a vector of the names of files in directory we set; in this case it'll create a vector with all the files that have the pattern "defor" on their names 
   rlist

   # 2 lapply: apply a function to a list
   list_rast <- lapply(rlist,brick)  # "lapply" creates a  list  where each element generated by applying the function (brick) correlate with the correspondent element in the vector (rlist) (it applies the function to the object)
   list_rast
   
   # basically, what we did was importing these 2 files separately
   
   
   plot(list_rast[[1]])   # the [[]] stands for linking the object (list_rast) to the value "1" in this case (almost like using a "$")
   
   # defor: NIR 1, red 2, green 3
   
   plotRGB(list_rast[[1]], r=1, g=2, b=3, stretch = "lin")  # plotRGB stands for  making true (or false) color images from Landsats satellite images
  
   l1992 <- list_rast[[1]]
   plotRGB(l1992 , r=1, g=2, b=3, stretch = "lin")
   
   l2006 <- list_rast[[2]]
   plotRGB(l2006 , r=1, g=2, b=3, stretch = "lin")
   
   
   
   # Unsupervised classification
   
   l1992c <- unsuperClass(l1992, nClasses=2)  # "unsuperClass" stands for classifying a file/object into a certain number of classes
   l1992c
   
   plot(l1992c$map)
   
   # value 1 = agricultural areas and water
   # value 2 = forests
   
   freq(l1992c$map)  # "freq" function shows us the amount of value 1 and 2 in the classification (the frequency of presence) ; using the "$" symbol, allows us to correlate an object to some specific data inside of it
   
   
   # total amount of pixels 
   
   total  <- 341292
   
   propagri <- 33662/total

   propforest <- 307630/total
   
   propagri
   propforest

   # agriculture and water :  0.09863108
   # forest : 0.9013689

  
  # build a data frame ( table )
  
  cover <- c("Forest", "Agriculture")
  prop1992  <- c( 0.09863108,  0.9013689)
  
  proportion1992  <- data.frame(cover, prop1992)
  proportion1992 
  
  
   
  ggplot(proportion1992, aes(x=cover, y=prop1992, color=cover)) + geom_bar(stat="identity", fill="white")
 

----------------------------------------------------- \\ ---------------------------- || ------------------------------- // ------------------------------------------

# day 3 (december 6)  - kind of a revision

library(raster)
library(RStoolbox) 
library(ggplot2)

setwd("C:/lab/")


# 1 list the files available

rlist <- list.files(pattern="defor")

rlist

list_rast <- lapply(rlist, brick) # lapply(x, FUN)

list_rast

# ---------------------------   For 1992 : ----------------------------------

l1992 <- list_rast[[1]]
plotRGB(l1992, r=1, g=2, b=3, stretch="lin")

l1992c <- unsuperClass(l1992, nClasses=2) # unsuperClass(x, nClasses)
l1992c

plot(l1992c$map)


freq(l1992c$map)
# value 2 = agricultural areas and water
# value 1 = forests

total <- 342726

#       value  count
# [1,]      1 306470
# [2,]      2  34822


propagri1992 <- 34822/total
propforest1992 <- 306470/total


# build a dataframe (table)

cover <- c("Agriculture", "Forest")   # since those are texts we use the " " and the "c" before since we're generating an array made of characters
prop1992 <- c(propagri1992, propforest1992)

proportion1992  <- data.frame(cover,prop1992)

plot1992 <- ggplot(proportion1992, aes(x=cover, y=prop1992, color=cover)) + geom_bar(stat="identity", fill="white")


# ------------------- For 2006 -------------------------:

l2006 <- list_rast[[2]]

l2006c <- unsuperClass(l2006, nClasses=2)  # unsuperClass(x, nClasses) ; Classification of the values for year of 2006
l2006c

plot(l2006c$map)

# Forest - value #1
# Agriculture - value #2

freq(l2006c$map)        # calcolating the fequencies for that year
#      value  count
# [1,]     1 178304  # forest
# [2,]     2 164422  # agriculture



total <- 342726   # this value was found by calling the file "l2006c" in the dimension field

propagri2006 <-  164422 /total
propforest2006 <- 178304/total

# building a data frame for  2006:

cover <- c("Agriculture", "Forest")
prop2006 <- c(propagri2006, propforest2006)

proportion2006 <- data.frame(cover, prop2006)   # table with the values for the year of 2006 

# ploting the proportion for 2006:

plot2006 <- ggplot(proportion2006, aes(x=cover, y=prop2006, color=cover)) + geom_bar(stat="identity", fill="white")



---------------------------------------------------------------------------------------------

# Now let's build a data frame with both values of proportion (from past and present):

proportion_final <- data.frame(cover, prop1992, prop2006)  # proportion_final generated a table with both proportions of the years 1992 and 2006 (as in some sort of comparison table)
proportion_final 

-------------------------------- \\ ---------- ||-------------- // ------------------

# ploting all together:

install.packages("gridExtra") 
library(gridExtra)

p1 <- ggplot(proportion_final, aes(x=cover, y=prop1992, color=cover)) + geom_bar(stat="identity", fill="white") + ylim(0,1)

p2 <- ggplot(proportion_final, aes(x=cover, y=prop2006, color=cover)) + geom_bar(stat="identity", fill="white") + ylim(0,1)



plot_final <- grid.arrange(p1, p2, nrows=1)   # "grid.arrange" stands for putting the graphs above all together (in the same multiframe) choosing a number n of rows/columns)
 












   
   
 
   
   
  
     
    
